# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webauction', '0002_auto_20180616_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='message_ptr',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
