# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webauction', '0004_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webauction.Auction')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('outBiddedBy', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outBidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='followedauction',
            unique_together=set([('auction', 'follower')]),
        ),
    ]
