# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 01:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauction', '0008_auto_20180617_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='premium_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
