# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauction', '0009_auction_premium_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='premium_active',
            field=models.BooleanField(default=False),
        ),
    ]
